Repository e-picsa/picsa-apps, pull requests merged in 2023-07, with the labels that each got.

#146 Feat(budget) Sidebar and Editor
  .github/workflows/web-preview.yml
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/cell-editor.html
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/cell-editor.scss
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/cell-editor.ts
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/input-values/input-values.html
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/input-values/input-values.scss
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/input-values/input-values.ts
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/next-button.ts
  apps/picsa-tools/budget-tool/src/app/components/balance/balance-legend/balance-legend.html
  apps/picsa-tools/budget-tool/src/app/components/balance/balance-legend/balance-legend.scss
  apps/picsa-tools/budget-tool/src/app/components/balance/balance-legend/balance-legend.ts
  apps/picsa-tools/budget-tool/src/app/components/budget-tool.components.ts
  apps/picsa-tools/budget-tool/src/app/components/editor-sidebar/editor-sidebar.component.html
  apps/picsa-tools/budget-tool/src/app/components/editor-sidebar/editor-sidebar.component.scss
  apps/picsa-tools/budget-tool/src/app/components/editor-sidebar/editor-sidebar.component.spec.ts
  apps/picsa-tools/budget-tool/src/app/components/editor-sidebar/editor-sidebar.component.ts
  apps/picsa-tools/budget-tool/src/app/components/editor/editor.component.html
  apps/picsa-tools/budget-tool/src/app/components/import-dialog/import-dialog.component.html
  apps/picsa-tools/budget-tool/src/app/components/summary/period-summary.html
  apps/picsa-tools/budget-tool/src/app/components/summary/period-summary.ts
  apps/picsa-tools/budget-tool/src/app/components/table/budget-table.html
  apps/picsa-tools/budget-tool/src/app/components/table/budget-table.scss
  apps/picsa-tools/budget-tool/src/app/components/table/budget-table.ts
  apps/picsa-tools/budget-tool/src/app/material.module.ts
  apps/picsa-tools/budget-tool/src/app/pages/create/budget-create.page.html
  apps/picsa-tools/budget-tool/src/app/pages/create/budget-create.page.scss
  apps/picsa-tools/budget-tool/src/app/pages/view/budget-view.module.ts
  apps/picsa-tools/budget-tool/src/app/pages/view/budget-view.page.html
  apps/picsa-tools/budget-tool/src/app/pages/view/budget-view.page.scss
  apps/picsa-tools/budget-tool/src/app/pages/view/budget-view.page.ts
  apps/picsa-tools/budget-tool/src/app/store/budget.store.ts
  apps/picsa-tools/climate-tool/src/app/components/climate-chart-options/climate-chart-options.component.html
  apps/picsa-tools/climate-tool/src/app/components/climate-chart-options/climate-chart-options.component.scss
  apps/picsa-tools/climate-tool/src/app/pages/site-view/site-view.page.html
  apps/picsa-tools/climate-tool/src/app/pages/site-view/site-view.page.ts
  libs/components/src/components/configuration-select/configuration-select.scss
  libs/components/src/components/picsa-header.component.scss
  libs/components/src/components/picsa-header.component.ts
  libs/components/src/components/picsa-sidenav.component.ts
  libs/components/src/module.ts
  libs/i18n/assets/debug.json
  libs/i18n/assets/en.json
  libs/i18n/assets/mw_ny.json
  libs/i18n/assets/sw.json
  libs/i18n/assets/tg.json
  libs/i18n/assets/zm_ny.json
  libs/i18n/src/hardcoded/budget.ts
  libs/i18n/templates/_template.csv
  libs/i18n/templates/_template.json
  libs/shared/src/features/dialog/components/TEMPLATES.ts
  libs/shared/src/features/dialog/components/action-dialog.html
  libs/shared/src/features/dialog/components/image-select.html
  libs/shared/src/features/dialog/dialog.models.ts
  libs/shared/src/features/dialog/dialog.module.ts
  libs/shared/src/features/dialog/dialog.service.ts
Labels: Feedback Discussion, Test - Preview

#148 Feat(probability-tool) Responsive table and translations
  .cspell.json
  apps/picsa-tools/crop-probability-tool/src/app/components/components.module.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.html
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.scss
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.spec.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.html
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.scss
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-select/crop-select.component.html
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-select/crop-select.component.scss
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-select/crop-select.component.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/station-select/station-select.component.html
  apps/picsa-tools/crop-probability-tool/src/app/data/crops.ts
  apps/picsa-tools/crop-probability-tool/src/app/data/mock.ts
  apps/picsa-tools/crop-probability-tool/src/app/models/index.ts
  libs/i18n/assets/debug.json
  libs/i18n/assets/en.json
  libs/i18n/assets/mw_ny.json
  libs/i18n/assets/sw.json
  libs/i18n/assets/tg.json
  libs/i18n/assets/zm_ny.json
  libs/i18n/src/hardcoded/index.ts
  libs/i18n/templates/_template.csv
  libs/i18n/templates/_template.json
Labels: Feedback Discussion, Test - Preview

#149 Feat/New stations
  apps/picsa-tools/crop-probability-tool/src/app/data/mock.ts
  apps/picsa-tools/resources-tool/src/app/data/picsa/cropInfo.ts
  apps/picsa-tools/resources-tool/src/assets/resources/contents.json
  apps/picsa-tools/resources-tool/src/assets/resources/crop-info-chipata.pdf
  apps/picsa-tools/resources-tool/src/assets/resources/crop-info-kasungu.pdf
  apps/picsa-tools/resources-tool/src/assets/resources/crop-info-nkhotakota.pdf
  apps/picsa-tools/resources-tool/src/assets/resources/crop-info-petauke.pdf
Labels: ready for review

#136 Feat/user data collections
  .github/workflows/web-preview.yml
  apps/picsa-apps/extension-app-native/android/app/build.gradle
  apps/picsa-apps/extension-app/src/app/pages/home/home.page.ts
  apps/picsa-apps/extension-app/src/app/store/user.store.ts
  apps/picsa-tools/option-tool/src/app/pages/home/home.component.ts
  apps/picsa-tools/option-tool/src/app/schemas/index.ts
  apps/picsa-tools/option-tool/src/app/schemas/schema_v0.ts
  apps/picsa-tools/option-tool/src/app/schemas/schema_v1.ts
  apps/picsa-tools/option-tool/src/app/services/options-tool.service.ts
  apps/picsa-tools/resources-tool/src/app/components/resource-item/resource-item.component.ts
  libs/components/src/components/profile-select/profile-select.component.html
  libs/components/src/components/profile-select/profile-select.component.ts
  libs/environments/src/version.ts
  libs/shared/src/services/core/appData.service.ts
  libs/shared/src/services/core/db_v2/db.service.ts
  libs/shared/src/services/core/user.service.ts
  package.json
Labels: Test - Preview

#151 Feat/crop probability crops
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.html
  apps/picsa-tools/crop-probability-tool/src/app/data/crops.ts
  apps/picsa-tools/crop-probability-tool/src/app/data/mock.ts
  apps/picsa-tools/crop-probability-tool/src/assets/svgs/crops/README.md
  libs/shared-assets/svgs/crops/beans.svg
  libs/shared-assets/svgs/crops/cotton.svg
  libs/shared-assets/svgs/crops/cowpeas.svg
  libs/shared-assets/svgs/crops/groundnuts.svg
  libs/shared-assets/svgs/crops/tobacco.svg
Labels: Feedback Discussion, Test - Preview

#152 Fix(budget) row headings and balance recalc
  apps/picsa-tools/budget-tool/src/app/components/editor/editor.component.html
  apps/picsa-tools/budget-tool/src/app/components/editor/editor.component.ts
  apps/picsa-tools/budget-tool/src/app/components/summary/period-summary.html
  apps/picsa-tools/budget-tool/src/app/components/summary/period-summary.ts
  apps/picsa-tools/budget-tool/src/app/components/table/budget-table.html
  apps/picsa-tools/budget-tool/src/app/components/table/budget-table.ts
  apps/picsa-tools/budget-tool/src/app/store/budget.store.ts
  apps/picsa-tools/budget-tool/src/app/store/templates.ts
Labels: Feedback Discussion

#157 Feat/climate chart updates
  apps/picsa-apps/content-dashboard/src/app/components/data-table/custom/data-table-station.ts
  apps/picsa-apps/content-dashboard/src/app/components/data-table/data-table.ts
  apps/picsa-apps/content-dashboard/src/app/pages/data-upload/data-upload.page.ts
  apps/picsa-apps/extension-app-native/android/app/build.gradle
  apps/picsa-tools/climate-tool/src/app/components/chart-layout/chart-layout.ts
  apps/picsa-tools/climate-tool/src/app/components/print-layout/print-layout.component.html
  apps/picsa-tools/climate-tool/src/app/components/print-layout/print-layout.component.ts
  apps/picsa-tools/climate-tool/src/app/components/share-dialog/share-dialog.component.html
  apps/picsa-tools/climate-tool/src/app/components/share-dialog/share-dialog.component.scss
  apps/picsa-tools/climate-tool/src/app/components/view-select/view-select.html
  apps/picsa-tools/climate-tool/src/app/components/view-select/view-select.scss
  apps/picsa-tools/climate-tool/src/app/components/view-select/view-select.ts
  apps/picsa-tools/climate-tool/src/app/data/definitions/colors.scss
  apps/picsa-tools/climate-tool/src/app/data/definitions/default.ts
  apps/picsa-tools/climate-tool/src/app/data/definitions/index.ts
  apps/picsa-tools/climate-tool/src/app/data/definitions/mw.ts
  apps/picsa-tools/climate-tool/src/app/data/definitions/zm.ts
  apps/picsa-tools/climate-tool/src/app/data/index.ts
  apps/picsa-tools/climate-tool/src/app/data/stations.ts
  apps/picsa-tools/climate-tool/src/app/models/chart-data.models.ts
  apps/picsa-tools/climate-tool/src/app/models/index.ts
  apps/picsa-tools/climate-tool/src/app/models/report.models.ts
  apps/picsa-tools/climate-tool/src/app/pages/site-select/site-select.page.ts
  apps/picsa-tools/climate-tool/src/app/pages/site-view/site-view.page.html
  apps/picsa-tools/climate-tool/src/app/pages/site-view/site-view.page.ts
  apps/picsa-tools/climate-tool/src/app/services/climate-chart.service.ts
  apps/picsa-tools/climate-tool/src/app/services/climate-data.service.ts
  apps/picsa-tools/climate-tool/src/assets/images/extreme-rainfall.svg
  libs/i18n/src/hardcoded/climate.ts
  libs/models/src/climate.models.ts
  package.json
Labels: Feedback Discussion

#159 Feat(climate) - chart-specific tool configuration
  apps/picsa-tools/climate-tool/src/app/components/chart-layout/chart-layout.html
  apps/picsa-tools/climate-tool/src/app/components/chart-tools/line-tool/line-tool.component.html
  apps/picsa-tools/climate-tool/src/app/components/chart-tools/line-tool/line-tool.component.ts
  apps/picsa-tools/climate-tool/src/app/components/chart-tools/line-tool/line-tool.model.ts
  apps/picsa-tools/climate-tool/src/app/components/chart-tools/probability-tool/probabililty-tool.model.ts
  apps/picsa-tools/climate-tool/src/app/components/chart-tools/probability-tool/probability-tool.html
  apps/picsa-tools/climate-tool/src/app/components/chart-tools/probability-tool/probability-tool.scss
  apps/picsa-tools/climate-tool/src/app/components/chart-tools/probability-tool/probability-tool.ts
  apps/picsa-tools/climate-tool/src/app/data/definitions/default.ts
  apps/picsa-tools/climate-tool/src/app/pages/site-view/site-view.page.ts
  apps/picsa-tools/climate-tool/src/app/services/climate-chart.service.ts
  apps/picsa-tools/climate-tool/src/app/services/climate-tool.service.ts
  libs/i18n/assets/debug.json
  libs/i18n/assets/en.json
  libs/i18n/assets/mw_ny.json
  libs/i18n/assets/sw.json
  libs/i18n/assets/tg.json
  libs/i18n/assets/zm_ny.json
  libs/i18n/templates/_template.csv
  libs/i18n/templates/_template.json
  libs/models/src/climate.models.ts
  libs/shared/src/modules/translate/translate.service.ts
  libs/theme/src/_overrides.scss
Labels: Feedback Discussion, Test - Preview

#163 Feat(manual) localised versions
  apps/picsa-apps/extension-app-native/android/app/build.gradle
  apps/picsa-tools/climate-tool/src/app/pages/site-view/site-view.page.ts
  apps/picsa-tools/climate-tool/src/app/services/climate-chart.service.ts
  apps/picsa-tools/manual-tool/src/app/components/pdf-viewer/pdf-viewer.component.html
  apps/picsa-tools/manual-tool/src/app/components/pdf-viewer/pdf-viewer.component.ts
  apps/picsa-tools/manual-tool/src/app/components/stepsContainer/stepsContainer.component.ts
  apps/picsa-tools/manual-tool/src/app/data/manual-contents.ts
  apps/picsa-tools/manual-tool/src/app/data/manual-resources.ts
  apps/picsa-tools/manual-tool/src/app/pages/home/home.component.html
  apps/picsa-tools/manual-tool/src/app/pages/home/home.component.ts
  apps/picsa-tools/manual-tool/src/app/pages/home/home.module.ts
  apps/picsa-tools/resources-tool/src/app/components/resource-item/resource-item.component.ts
  apps/picsa-tools/resources-tool/src/app/data/picsa/manuals.ts
  apps/picsa-tools/resources-tool/src/app/stores/resources.store.ts
  libs/components/src/components/alert-box/alert-box.component.html
  libs/components/src/components/alert-box/alert-box.component.ts
  libs/components/src/components/back-button.component.ts
  libs/components/src/services/components.service.ts
  libs/environments/src/version.ts
  libs/i18n/assets/debug.json
  libs/i18n/assets/en.json
  libs/i18n/assets/mw_ny.json
  libs/i18n/assets/sw.json
  libs/i18n/assets/tg.json
  libs/i18n/assets/zm_ny.json
  libs/i18n/templates/_template.csv
  libs/i18n/templates/_template.json
  libs/shared/src/services/native/storage-service.ts
  package.json
Labels: Test - Preview

#170 Feat/zm updates
  apps/picsa-apps/extension-app-native/android/app/build.gradle
  apps/picsa-apps/extension-app/project.json
  apps/picsa-tools/climate-tool/src/app/components/chart-tools/probability-tool/probabililty-tool.model.ts
  apps/picsa-tools/manual-tool/src/app/components/material.module.ts
  apps/picsa-tools/manual-tool/src/app/components/stepsContainer/stepsContainer.component.html
  apps/picsa-tools/manual-tool/src/app/components/stepsContainer/stepsContainer.component.ts
  apps/picsa-tools/manual-tool/src/app/data/index.ts
  apps/picsa-tools/manual-tool/src/app/data/manual-contents/common.ts
  apps/picsa-tools/manual-tool/src/app/data/manual-contents/extension.ts
  apps/picsa-tools/manual-tool/src/app/data/manual-contents/farmer.ts
  apps/picsa-tools/manual-tool/src/app/data/manual-contents/index.ts
  apps/picsa-tools/manual-tool/src/app/pages/activity-details/activity-details.component.ts
  apps/picsa-tools/manual-tool/src/app/pages/activity/activity.component.ts
  apps/picsa-tools/manual-tool/src/app/pages/home/home.component.html
  apps/picsa-tools/manual-tool/src/app/pages/home/home.component.ts
  apps/picsa-tools/monitoring-tool/data/forms/ew-monitoring-mw.form.ts
  apps/picsa-tools/monitoring-tool/data/forms/ew-monitoring-zm.form.ts
  apps/picsa-tools/monitoring-tool/data/forms/ew-monitoring.form.ts
  apps/picsa-tools/monitoring-tool/data/forms/index.ts
  apps/picsa-tools/resources-tool/src/app/data/picsa/manuals.ts
  apps/picsa-tools/resources-tool/src/app/data/weather/index.ts
  apps/picsa-tools/resources-tool/src/app/data/weather/links.ts
  apps/picsa-tools/resources-tool/src/app/data/workshops/mw-salima-2022.ts
  apps/picsa-tools/resources-tool/src/app/models/index.ts
  apps/picsa-tools/resources-tool/src/app/pages/collection/collection.component.ts
  apps/picsa-tools/resources-tool/src/app/stores/resources.store.ts
  apps/picsa-tools/resources-tool/src/assets/resources/contents.json
  apps/picsa-tools/resources-tool/src/assets/resources/covers/workshop-salima-2022.jpg
  apps/picsa-tools/resources-tool/src/assets/resources/picsa-manual-farmer.pdf
  apps/picsa-tools/resources-tool/src/assets/resources/potential-PICSA-training-schedule-cover.png
  apps/picsa-tools/resources-tool/src/assets/resources/potential-PICSA-training-scheduled.pdf
  libs/environments/src/version.ts
  libs/i18n/assets/debug.json
  libs/i18n/assets/en.json
  libs/i18n/assets/mw_ny.json
  libs/i18n/assets/sw.json
  libs/i18n/assets/tg.json
  libs/i18n/assets/zm_ny.json
  libs/i18n/templates/_template.csv
  libs/i18n/templates/_template.json
  package.json
  yarn.lock
Labels: Feedback Discussion
