Repository e-picsa/picsa-apps, pull requests merged in 2023-05, with the labels that each got.

#129 Feat: User Profiles
  .vscode/settings.json
  apps/picsa-apps/extension-app-native/android/app/build.gradle
  apps/picsa-apps/extension-app/src/app/pages/home/home.page.html
  apps/picsa-apps/extension-app/src/app/pages/home/home.page.scss
  apps/picsa-apps/extension-app/src/app/pages/home/home.page.ts
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/input-values/input-values.html
  apps/picsa-tools/budget-tool/src/app/components/card/card-new/card-new-dialog.html
  apps/picsa-tools/budget-tool/src/app/components/editor/card-editor/card-editor.component.html
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/family-labour/family-labour.html
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/produce-consumed/produce-consumed.html
  apps/picsa-tools/budget-tool/src/app/components/editor/editor.component.ts
  apps/picsa-tools/crop-probability-tool/project.json
  apps/picsa-tools/monitoring-tool/project.json
  apps/picsa-tools/option-tool/project.json
  libs/components/src/components/configuration-select/configuration-select-dialog.html
  libs/components/src/components/configuration-select/configuration-select-dialog.scss
  libs/components/src/components/picsa-header.component.scss
  libs/components/src/components/picsa-header.component.ts
  libs/components/src/components/profile-select/profile-select.component.html
  libs/components/src/components/profile-select/profile-select.component.scss
  libs/components/src/components/profile-select/profile-select.component.spec.ts
  libs/components/src/components/profile-select/profile-select.component.ts
  libs/components/src/module.ts
  libs/environments/src/version.ts
  libs/i18n/assets/en.json
  libs/i18n/assets/ny.json
  libs/i18n/assets/sw.json
  libs/i18n/assets/tg.json
  libs/i18n/src/hardcoded/common.ts
  libs/i18n/templates/_template.csv
  libs/i18n/templates/_template.json
  libs/theme/src/_layout.scss
  libs/theme/src/_overrides.scss
  libs/utils/data.ts
  package.json
  yarn.lock
Labels: Feedback Discussion, Test - Preview

#130 Feat(crop-probability): Filter Icons
  apps/picsa-apps/extension-app-native/android/app/src/main/assets/capacitor.config.json
  apps/picsa-apps/extension-app/project.json
  apps/picsa-tools/budget-tool/project.json
  apps/picsa-tools/crop-probability-tool/project.json
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.html
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.scss
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/material.module.ts
  apps/picsa-tools/crop-probability-tool/src/assets/svgs/crops/README.md
  apps/picsa-tools/resources-tool/src/assets/resources/contents.json
  libs/shared-assets/svgs/crops/avocado.svg
  libs/shared-assets/svgs/crops/beans.svg
  libs/shared-assets/svgs/crops/cowpeas.svg
  libs/shared-assets/svgs/crops/groundnuts.svg
  libs/shared-assets/svgs/crops/maize.svg
  libs/shared-assets/svgs/crops/mangoes.svg
  libs/shared-assets/svgs/crops/onions.svg
  libs/shared-assets/svgs/crops/paw-paw.svg
  libs/shared-assets/svgs/crops/pigeon-peas.svg
  libs/shared-assets/svgs/crops/pumpkins.svg
  libs/shared-assets/svgs/crops/rice.svg
  libs/shared-assets/svgs/crops/soya-beans.svg
  libs/shared-assets/svgs/crops/sunflower.svg
  libs/shared-assets/svgs/crops/sweet-potatoes.svg
  libs/shared-assets/svgs/crops/tomatoes.svg
  yarn.lock
Labels: Feedback Discussion

#131 Feat/options rxdb connection
  apps/picsa-apps/extension-app/src/app/app.module.ts
  apps/picsa-tools/option-tool/src/app/app.module.ts
  apps/picsa-tools/option-tool/src/app/components/editor/editor.component.html
  apps/picsa-tools/option-tool/src/app/components/editor/editor.component.scss
  apps/picsa-tools/option-tool/src/app/pages/home/home.component.html
  apps/picsa-tools/option-tool/src/app/pages/home/home.component.scss
  apps/picsa-tools/option-tool/src/app/pages/home/home.component.ts
  apps/picsa-tools/option-tool/src/app/pages/home/home.module.ts
  apps/picsa-tools/option-tool/src/app/schemas/schema_v0.ts
  apps/picsa-tools/option-tool/src/app/services/options-tool.service.ts
  libs/i18n/assets/en.json
  libs/i18n/assets/mw_ny.json
  libs/i18n/assets/sw.json
  libs/i18n/assets/tg.json
  libs/i18n/assets/zm_ny.json
  libs/i18n/templates/_template.csv
  libs/i18n/templates/_template.json
  libs/shared/src/modules/database_v2/db.module.ts
  libs/shared/src/modules/index.ts
  libs/shared/src/services/core/db_v2/db.service.ts
  libs/shared/src/services/core/db_v2/index.ts
  package.json
  yarn.lock
Labels: Test - Preview, ready for review

#134 Feat/dynamic crop probability display
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.html
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.scss
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.html
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.scss
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/material.module.ts
  apps/picsa-tools/crop-probability-tool/src/app/data/icons.ts
  apps/picsa-tools/crop-probability-tool/src/app/data/mock.ts
  apps/picsa-tools/crop-probability-tool/src/app/models/index.ts
  libs/shared-assets/svgs/crops/sorghum.svg
Labels: Test - Preview, ready for review
