Repository e-picsa/picsa-apps, pull requests merged in 2023-04, with the labels that each got.

#120 feat: integrate option tool with extension toolkit
  apps/picsa-apps/extension-app-native/android/app/build.gradle
  apps/picsa-apps/extension-app/project.json
  apps/picsa-apps/extension-app/src/app/app-routing.module.ts
  apps/picsa-tools/monitoring-tool/src/app/app.component.ts
  apps/picsa-tools/option-tool/project.json
  apps/picsa-tools/option-tool/src/app/app-routing.module.ts
  apps/picsa-tools/option-tool/src/app/app.component.html
  apps/picsa-tools/option-tool/src/app/app.component.spec.ts
  apps/picsa-tools/option-tool/src/app/app.component.ts
  apps/picsa-tools/option-tool/src/app/app.module-embedded.ts
  apps/picsa-tools/option-tool/src/app/app.module.ts
  apps/picsa-tools/option-tool/src/app/components/components.module.ts
  apps/picsa-tools/option-tool/src/app/components/material.module.ts
  apps/picsa-tools/option-tool/src/app/material.module.ts
  apps/picsa-tools/option-tool/src/app/pages/home/home.module.ts
  apps/picsa-tools/option-tool/src/index.html
  libs/components/src/components/picsa-header.component.ts
  libs/configuration/src/provider.ts
  libs/environments/src/version.ts
  package.json
  tsconfig.base.json
Labels: Test - Preview

#121 Ft Crop-information-tool
  .gitignore
  apps/picsa-tools/crop-probability-tool/src/app/app.module.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.html
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.scss
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.spec.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table-header/crop-probability-table-header.component.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.html
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.scss
  apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.ts
  apps/picsa-tools/crop-probability-tool/src/app/components/material.module.ts
  apps/picsa-tools/crop-probability-tool/src/app/data/mock.ts
  yarn.lock
Labels: Feedback Discussion, ready for review

#122 Feat/option tool autosave
  apps/picsa-apps/farmer-app-e2e/tsconfig.json
  apps/picsa-apps/farmer-app/tsconfig.json
  apps/picsa-tools/crop-probability-tool-e2e/tsconfig.json
  apps/picsa-tools/crop-probability-tool/tsconfig.json
  apps/picsa-tools/monitoring-tool-e2e/tsconfig.json
  apps/picsa-tools/option-tool-e2e/tsconfig.json
  apps/picsa-tools/option-tool/src/app/components/editor/editor.component.html
  apps/picsa-tools/option-tool/src/app/components/editor/editor.component.scss
  apps/picsa-tools/option-tool/src/app/components/editor/editor.component.ts
  apps/picsa-tools/option-tool/src/app/pages/home/home.component.html
  apps/picsa-tools/option-tool/src/app/pages/home/home.component.scss
  apps/picsa-tools/option-tool/src/app/pages/home/home.component.ts
  apps/picsa-tools/option-tool/tsconfig.json
  libs/webcomponents-ngx/tsconfig.json
Labels: ready for review

#116 Feat(budget): Editor Improvements
  .eslintrc.json
  apps/picsa-apps/extension-app-native/android/app/build.gradle
  apps/picsa-tools/budget-tool/.eslintrc.json
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/input-values/input-values.html
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/input-values/input-values.scss
  apps/picsa-tools/budget-tool/src/app/components/_deprecated/input-values/input-values.ts
  apps/picsa-tools/budget-tool/src/app/components/budget-tool.components.ts
  apps/picsa-tools/budget-tool/src/app/components/card/budget-card.html
  apps/picsa-tools/budget-tool/src/app/components/card/budget-card.scss
  apps/picsa-tools/budget-tool/src/app/components/card/budget-card.ts
  apps/picsa-tools/budget-tool/src/app/components/card/card-placeholder/card-placeholder.component.html
  apps/picsa-tools/budget-tool/src/app/components/card/card-placeholder/card-placeholder.component.scss
  apps/picsa-tools/budget-tool/src/app/components/card/card-placeholder/card-placeholder.component.spec.ts
  apps/picsa-tools/budget-tool/src/app/components/card/card-placeholder/card-placeholder.component.ts
  apps/picsa-tools/budget-tool/src/app/components/cell-editor/produce-consumed/produce-consumed.html
  apps/picsa-tools/budget-tool/src/app/components/cell-editor/produce-consumed/produce-consumed.ts
  apps/picsa-tools/budget-tool/src/app/components/cell-inline-editor/cell-inline-editor.component.html
  apps/picsa-tools/budget-tool/src/app/components/cell-inline-editor/cell-inline-editor.component.scss
  apps/picsa-tools/budget-tool/src/app/components/cell-inline-editor/cell-inline-editor.component.spec.ts
  apps/picsa-tools/budget-tool/src/app/components/cell-inline-editor/cell-inline-editor.component.ts
  apps/picsa-tools/budget-tool/src/app/components/editor/card-editor/card-editor.component.html
  apps/picsa-tools/budget-tool/src/app/components/editor/card-editor/card-editor.component.scss
  apps/picsa-tools/budget-tool/src/app/components/editor/card-editor/card-editor.component.spec.ts
  apps/picsa-tools/budget-tool/src/app/components/editor/card-editor/card-editor.component.ts
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/card-select.html
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/card-select.scss
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/card-select.ts
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/family-labour/family-labour.html
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/family-labour/family-labour.scss
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/family-labour/family-labour.ts
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/produce-consumed/produce-consumed.html
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/produce-consumed/produce-consumed.scss
  apps/picsa-tools/budget-tool/src/app/components/editor/card-select/produce-consumed/produce-consumed.ts
  apps/picsa-tools/budget-tool/src/app/components/editor/editor.component.html
  apps/picsa-tools/budget-tool/src/app/components/editor/editor.component.scss
  apps/picsa-tools/budget-tool/src/app/components/editor/editor.component.spec.ts
  apps/picsa-tools/budget-tool/src/app/components/editor/editor.component.ts
  apps/picsa-tools/budget-tool/src/app/models/budget-tool.models.ts
  apps/picsa-tools/budget-tool/src/app/pages/view/budget-view.page.html
  apps/picsa-tools/budget-tool/src/app/pages/view/budget-view.page.ts
  apps/picsa-tools/budget-tool/src/app/store/budget.store.ts
  apps/picsa-tools/budget-tool/src/styles.scss
  libs/components/src/components/picsa-header.component.ts
  libs/components/src/services/components.service.ts
  libs/environments/src/version.ts
  libs/i18n/assets/en.json
  libs/i18n/assets/ny.json
  libs/i18n/assets/sw.json
  libs/i18n/assets/tg.json
  libs/i18n/templates/_template.csv
  libs/i18n/templates/_template.json
  libs/shared/src/animations/animations.ts
  libs/theme/src/_overrides.scss
  package.json
  yarn.lock
Labels: Feedback Discussion, Test - Preview

#127 Feat/option tool transilation
  .cspell.json
  apps/picsa-tools/option-tool/project.json
  apps/picsa-tools/option-tool/src/app/components/editor/editor.component.html
  apps/picsa-tools/option-tool/src/app/pages/home/home.component.html
  apps/picsa-tools/option-tool/src/app/pages/home/home.module.ts
  libs/i18n/assets/en.json
  libs/i18n/assets/ny.json
  libs/i18n/assets/sw.json
  libs/i18n/assets/tg.json
  libs/i18n/project.json
  libs/i18n/src/generate.ts
  libs/i18n/src/hardcoded/common.ts
  libs/i18n/src/hardcoded/index.ts
  libs/i18n/src/types.ts
  libs/i18n/templates/_template.csv
  libs/i18n/templates/_template.json
  libs/webcomponents-ngx/src/lib/generated/components.ts
  package.json
  yarn.lock
Labels: ready for review
