Repository e-picsa/picsa-apps, pull requests merged in 2023-06, with the labels that each got.

#141 Feat(manual) - extension tool version
  apps/picsa-apps/extension-app-native/android/app/build.gradle
  apps/picsa-apps/extension-app/project.json
  apps/picsa-apps/extension-app/src/app/material.module.ts
  apps/picsa-apps/extension-app/src/app/pages/home/home.page.ts
  apps/picsa-apps/extension-app/src/assets/images/budget-create.svg
  apps/picsa-apps/extension-app/src/assets/images/not used/settings (1).svg
  apps/picsa-apps/extension-app/src/assets/images/option-tool.svg
  apps/picsa-apps/extension-app/src/assets/images/probability-tool.svg
  apps/picsa-apps/extension-app/src/assets/svgs/budget_tool.svg
  apps/picsa-apps/extension-app/src/assets/svgs/climate_tool.svg
  apps/picsa-apps/extension-app/src/assets/svgs/data_collection.svg
  apps/picsa-apps/extension-app/src/assets/svgs/discussions.svg
  apps/picsa-apps/extension-app/src/assets/svgs/manual_tool.svg
  apps/picsa-apps/extension-app/src/assets/svgs/option_tool.svg
  apps/picsa-apps/extension-app/src/assets/svgs/probability_tool.svg
  apps/picsa-apps/extension-app/src/assets/svgs/resources_tool.svg
  apps/picsa-apps/extension-app/src/assets/svgs/whatsapp.svg
  apps/picsa-tools/manual-tool/project.json
  apps/picsa-tools/manual-tool/src/app/components/components.module.ts
  apps/picsa-tools/manual-tool/src/app/components/pdf-viewer/pdf-viewer.component.html
  apps/picsa-tools/manual-tool/src/app/components/pdf-viewer/pdf-viewer.component.scss
  apps/picsa-tools/manual-tool/src/app/components/pdf-viewer/pdf-viewer.component.spec.ts
  apps/picsa-tools/manual-tool/src/app/components/pdf-viewer/pdf-viewer.component.ts
  apps/picsa-tools/manual-tool/src/app/components/stepsContainer/stepsContainer.component.html
  apps/picsa-tools/manual-tool/src/app/components/stepsContainer/stepsContainer.component.scss
  apps/picsa-tools/manual-tool/src/app/components/stepsContainer/stepsContainer.component.ts
  apps/picsa-tools/manual-tool/src/app/data/manual-contents.ts
  apps/picsa-tools/manual-tool/src/app/pages/home/home.component.html
  apps/picsa-tools/manual-tool/src/app/pages/home/home.component.scss
  apps/picsa-tools/manual-tool/src/app/pages/home/home.component.ts
  apps/picsa-tools/manual-tool/src/app/pages/home/home.module.ts
  apps/picsa-tools/manual-tool/src/assets/resources/README.md
  apps/picsa-tools/manual-tool/src/assets/svgs/calender.svg
  apps/picsa-tools/manual-tool/src/assets/svgs/campus.svg
  apps/picsa-tools/manual-tool/src/assets/svgs/crop.svg
  apps/picsa-tools/manual-tool/src/assets/svgs/livestock.svg
  apps/picsa-tools/manual-tool/src/assets/svgs/place_holder.svg
  apps/picsa-tools/manual-tool/src/assets/svgs/resourceAllocation.svg
  apps/picsa-tools/manual-tool/src/assets/svgs/temperature.svg
  libs/environments/src/version.ts
  libs/i18n/assets/en.json
  libs/i18n/assets/mw_ny.json
  libs/i18n/assets/sw.json
  libs/i18n/assets/tg.json
  libs/i18n/assets/zm_ny.json
  libs/i18n/src/hardcoded/index.ts
  libs/i18n/templates/_template.csv
  libs/i18n/templates/_template.json
  package.json
  yarn.lock
Labels: Feedback Discussion, Test - Preview

#142 Add routing for manual activity
  apps/picsa-tools/manual-tool/src/app/app-routing.module.ts
  apps/picsa-tools/manual-tool/src/app/components/pdf-viewer/pdf-viewer.component.html
  apps/picsa-tools/manual-tool/src/app/components/stepsContainer/stepsContainer.component.html
  apps/picsa-tools/manual-tool/src/app/components/stepsContainer/stepsContainer.component.scss
  apps/picsa-tools/manual-tool/src/app/components/stepsContainer/stepsContainer.component.ts
  apps/picsa-tools/manual-tool/src/app/data/manual-contents.ts
  apps/picsa-tools/manual-tool/src/app/pages/activity-details/activity-details.component.html
  apps/picsa-tools/manual-tool/src/app/pages/activity-details/activity-details.component.scss
  apps/picsa-tools/manual-tool/src/app/pages/activity-details/activity-details.component.spec.ts
  apps/picsa-tools/manual-tool/src/app/pages/activity-details/activity-details.component.ts
  apps/picsa-tools/manual-tool/src/app/pages/activity/activity.component.html
  apps/picsa-tools/manual-tool/src/app/pages/activity/activity.component.scss
  apps/picsa-tools/manual-tool/src/app/pages/activity/activity.component.spec.ts
  apps/picsa-tools/manual-tool/src/app/pages/activity/activity.component.ts
  apps/picsa-tools/manual-tool/src/app/pages/activity/activity.module.ts
  apps/picsa-tools/resources-tool/src/assets/resources/contents.json
Labels: ready for review

#145 feat(translations): add translator app configuration
  libs/configuration/src/configurations/global.ts
  libs/i18n/assets/debug.json
  libs/i18n/source/debug.json
Labels: Feedback Discussion
